version: "3.3"

services:
  dislinkt:
    build: ./
    ports:
      - "12345:12345"
    environment:
      MONGODB_URI: mongo:27017
    restart: always
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
  